What is NumPy?
NumPy (Numerical Python) is used for working with:

Arrays (1D, 2D, ND)

Linear algebra

Statistics

Random number generation

Broadcasting (fast operations)

In [1]:
import numpy as np

In [2]:
# 1D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
# Basic Operations
print("mean: ", np.mean(arr))
print("standard deviation: ", np.std(arr))
print("max value: ", np.max(arr))
print("Total: ", np.sum(arr))

mean:  3.0
standard deviation:  1.4142135623730951
max value:  5
Total:  15


In [4]:
# 2D array.

matrix = np.array([[1,2], [4,5]])

#Matrix Transpose.

print("Transpose:\n", matrix.T)
print("Dot product:\n", np.dot(matrix, matrix))


Transpose:
 [[1 4]
 [2 5]]
Dot product:
 [[ 9 12]
 [24 33]]


🎲 5. Random Number Generation

In [5]:
random_arr = np.random.randint(1,100, size = (3,3))
print("Random Array\n", random_arr)

Random Array
 [[58 72 32]
 [11 22 66]
 [67 24 51]]


🧠 6. Shape & Reshape

In [6]:
arr = np.arange(12)
reshaped = arr.reshape(3,4)
print("reshaped array:\n", reshaped)

reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


...................Exercise....................

In [7]:
# 1D array
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [8]:
# 2D array
arr2 = np.array([[2,4], [6,8]])
print(arr2)

[[2 4]
 [6 8]]


In [9]:
# Basics math operations..
print("Mean: ", np.mean(arr1))
print("Standard Deviation: ", np.round(np.std(arr1),2))
print("Max Value: ", np.max(arr1))
print("Min Value: ", np.min(arr1))
print("Sum: ", np.sum(arr1))
print("Variance: ", np.round(np.var(arr1),2))


Mean:  5.0
Standard Deviation:  2.58
Max Value:  9
Min Value:  1
Sum:  45
Variance:  6.67


In [10]:
# Generate Random Arrays
arr3 = np.random.randint(100,1000, size = (3,3))
print(arr3)

[[111 112 948]
 [777 942 708]
 [439 108 967]]


In [11]:
# Reshaping the array
arr4 = np.arange(1,21)

In [12]:
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
reshaped2 = arr4.reshape(5,4)
print(reshaped2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
